FORMAT: 1A
HOST: http://friendfinder.zazoapp.com/

# Zazo FriendFinder

## Authentication

The default mehtod is **HTTP Digest** with service's `username` and `password`.

The **HTTP Basic** works only for `development` environment (as in examples).

## Contacts [/api/v1/contacts]

### Add Contact List [POST /{?contacts}]

Validate and save contact list into database.

+ Parameters
    + contacts (array) - array of contacts with specific contact structure:
        + display_name (string) - user name as it shows in phone contact list
        + additions (hash) - contact specific attributes from the allowed list
        + vectors (array) - different communication vectors by contact:
            + name (string) - name of vector
            + value (string) - value of vector
            + additions (hash) - vector specific attributes from the allowed list

+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
            
    + Body

            {
                "contacts": [
                    {
                        "display_name": "Sani El-Fishawy",
                        "additions": {
                            "marked_as_favorite": true
                        }
                        "vectors": [
                            {
                                "name": "mobile",
                                "value": "+16502453537",
                                "additions": {
                                    "sms_messages_sent": 15
                                }
                            }, {
                                "name": "email",
                                "value": "elfishawy.sani@gmail.com",
                                "additions": {
                                    "email_messages_sent": 23
                                }
                            }
                        ]
                    }
                ]
            }

+ Response 200 (application/json)

        {
            "status": "success"
        }

+ Request Failure (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
            
    + Body

            {
                "contacts": [
                    {
                        "display_name": "Sani El-Fishawy",
                        "additions": {
                            "email_messages_sent": 23
                        }
                        "vectors": [
                            {
                                "name": "email",
                                "value": "asdasd@asdasd",
                                "additions": {
                                    "sms_messages_sent": 15
                                }
                            }, {
                                "name": "mobile",
                                "value": "xxxxxxxxx",
                                "additions": {
                                    "email_messages_sent": 23
                                }
                            }
                        ]
                    }
                ]
            }
            
+ Response 422 (application/json;)

        {
            "status": "failure",
            "errors": {
                "vectors": [
                    {
                        "additions": ["'sms_messages_sent' is not allowed condition for 'email' vector"],
                        "value": ["'asdasd@asdasd' has incorrect format for 'email' vector"]
                    },
                    {
                        "additions": ["'email_messages_sent' is not allowed condition for 'mobile' vector"],
                        "value": ["'xxxxxxxxx' has incorrect format for 'mobile' vector"]
                    }
                ],
                "contacts": [
                    "additions": ["'email_messages_sent' is not allowed addition"]
                ]
            }
        }
        
+ Request Unauthorized (application/json)

+ Response 401 (application/json)

        {
            "status": "unauthorized"
        }
        
## Suggestions [/api/v1/suggestions]

### Get Suggestions List [GET]

Return contacts in order by total score by all criterias.
        
+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
        
+ Response 200 (application/json)

        {
            "status": "success",
            "data": [
                {
                    "id": 1,
                    "first_name": null,
                    "last_name": null,
                    "display_name": "Sani El-Fishawy",
                    "zazo_mkey": "7qdanSEmctZ2jPnYA0a1",
                    "zazo_id": 1,
                    "total_score": 164
                }, {
                    "id": 2,
                    "first_name": nil,
                    "last_name": nil,
                    "display_name": "Ivan",
                    "zazo_mkey": nil,
                    "zazo_id": nil,
                    "total_score": 26
                }
            ]
        }
        
+ Request Unauthorized (application/json)

+ Response 401 (application/json)

        {
            "status": "unauthorized"
        }
        
### Reject Contacts Suggestions [POST /reject{?rejected}]

Reject contacts by contact id (see `data->id` in **Get Suggestions List** response).

+ Parameters
    + rejected (array) - array of contacts ids to reject suggestions

+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
            
    + Body

            {
                "rejected": [1, 2, 3]
            }

+ Response 200 (application/json)

        {
            "status": "success"
        }

+ Request Failure (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
            
    + Body

            {
                "rejected": 1
            }

+ Response 422 (application/json)

        {
            "status": "failure",
            "errors": {
                "raw_params": ["raw_params['rejected'] must be type of Array"]
            }
        }
        
+ Request Failure (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
            
    + Body

            {
                "rejected": [1982]
            }

+ Response 422 (application/json)

        {
            "status": "failure",
            "errors": {
                "raw_params_id": ["contact with id=1982 is not exist"]
            }
        }
        
+ Request Unauthorized (application/json)

+ Response 401 (application/json)

        {
            "status": "unauthorized"
        }
        
### Recommend Contact [POST /recommend{?recommendations}]

Recommend specific zazo-user (freshly invited) to others zazo-friends.

+ Parameters
    + recommendations
        + contact_mkey (string) - contact mkey to recommend
        + to_mkeys (array) - array of string of contacts (mkeys), which an another contact (**contact_mkey**) will be recommended to

+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
            
    + Body

            {
                "recommendations": {
                    "contact_mkey": "0DAQEVtmNKQiW6aoQrvo",
                    "to_mkeys": [
                        "7qdanSEmctZ2jPnYA0a1",
                        "dz4X0EvprPJO6fGysT8X"
                    ]
                }
            }

+ Response 200 (application/json)

        {
            "status": "success"
        }
        
+ Request Failure (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
            
    + Body

            {
                "recommendations": {
                    "contact_mkey": "0DAQEVtmNKQiW6aoQrvo",
                    "to_mkeys": "7qdanSEmctZ2jPnYA0a1"
                }
            }

+ Response 422 (application/json)

        {
            "status": "failure",
            "errors": {
                "raw_params": ["raw_params['to_mkeys'] must be type of Array"]
            }
        }
        
+ Request Failure (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
            
    + Body

            {
                "recommendations": {
                    "to_mkeys": [
                        "7qdanSEmctZ2jPnYA0a1",
                        "dz4X0EvprPJO6fGysT8X"
                    ]
                }
            }

+ Response 422 (application/json)

        {
            "status": "failure",
            "errors": {
                "raw_params": ["raw_params['contact_mkey'] must be present"]
            }
        }
        
+ Request Unauthorized (application/json)

+ Response 401 (application/json)

        {
            "status": "unauthorized"
        }
