FORMAT: 1A
HOST: http://ff.zazoapp.com

# Zazo FriendFinder

## Authentication

The default mehtod is **HTTP Digest** with service's `username` and `password`.

## Contacts [/api/v1/contacts]

### Get Info [GET /api/v1/contacts/{id}]

Get all information about contact by `id`.

+ Parameters
    + id (integer) - id of contact

+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": 1149,
                "first_name": null,
                "last_name": null,
                "display_name": "Ralph",
                "zazo_mkey": null,
                "zazo_id": null,
                "total_score": null,
                "vectors": [
                    {
                        "name": "mobile",
                        "value": "+12345678910",
                        "additions": {}
                    }
                ]
            }
        }

+ Request Failure (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=

+ Response 422 (application/json)

        {
            "status": "failure",
            "errors": {
                "contact_id": ["not found by id=114"]
            }
        }

+ Request Failure (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=

+ Response 422 (application/json)

        {
            "status": "failure",
            "errors": {
                "contact_id": ["not belongs to owner"]
            }
        }
        
+ Request Unauthorized (application/json)

+ Response 401 (application/json)

        {
            "status": "unauthorized"
        }

### Import Contacts [POST]

Validate and save contacts list (via background job) into database.

+ Parameters
    + contacts (array) - array of contacts with specific contact structure:
        + display_name (string) - user name as it shows in phone contact list
        + additions (hash) - contact specific attributes from the allowed list
        + vectors (array) - different communication vectors by contact:
            + name (string) - name of vector
            + value (string) - value of vector
            + additions (hash) - vector specific attributes from the allowed list

+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
            
    + Body

            {
                "contacts": [
                    {
                        "display_name": "Sani El-Fishawy",
                        "additions": {
                            "marked_as_favorite": true
                        }
                        "vectors": [
                            {
                                "name": "mobile",
                                "value": "+16502453537",
                                "additions": {
                                    "sms_messages_sent": 15
                                }
                            }, {
                                "name": "email",
                                "value": "elfishawy.sani@gmail.com",
                                "additions": {
                                    "email_messages_sent": 23
                                }
                            }
                        ]
                    }
                ]
            }

+ Response 200 (application/json)

        {
            "status": "success"
        }

+ Request Failure (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
            
    + Body

            {
                "contacts": [
                    {
                        "display_name": "Sani El-Fishawy",
                        "vectors": []
                    }
                ]
            }
            
+ Response 422 (application/json)

        {
            "status": "failure",
            "errors": {
                "invalid_contacts": [
                    {
                        "display_name": "Sani El-Fishawy",
                        "vectors":null
                    }
                ]
            }
        }
        
+ Request Unauthorized (application/json)

+ Response 401 (application/json)

        {
            "status": "unauthorized"
        }

### Add Contact [POST /api/v1/contacts/{id}/add]

Add contact as friends on Zazo by contact id (see `response["data"][i]["id"]` in **Get Suggestions List** response).

Status of contact addition (see `response["data"]["status"]` in current **Response** `200`)
may have different values: "added", "already_added", "not_added", "queued", "error".

+ Parameters
    + phone_number (optional, string) - specific phone number to add contact

+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
            
    + Body

            {
                "phone_number": "+12345057023"
            }

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
              "id": "22",
              "mkey": "2BRYlvycJOkDcnnelFUz",
              "first_name": "David",
              "last_name": "Bowie",
              "mobile_number": "+12345057023",
              "device_platform": null,
              "emails": [],
              "has_app": "false",
              "ckey": "2_22_Cregi20UjeMSnpS5bXa0",
              "cid": "21",
              "connection_created_on": "2016-04-26T14:35:39Z",
              "connection_creator_mkey": "7qdanSEmctZ2jPnYA0a1",
              "connection_status": "established",
              "status": "added"
            }
        }

+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
              "status": "already_added"
            }
        }

+ Request Failure (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=

+ Response 422 (application/json)

        {
            "status": "failure",
            "errors": {
                "contact_id": ["not found by id=123"]
            }
        }
        
+ Request Failure (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=

+ Response 422 (application/json)

        {
            "status": "failure",
            "errors": {
                "contact_id": ["you are not owner of contact id=123"]
            }
        }
        
+ Request Unauthorized (application/json)

+ Response 401 (application/json)

        {
            "status": "unauthorized"
        }

### Ignore Contact [POST /api/v1/contacts/{id}/ignore]

Ignore contact by contact id (see `response["data"][i]["id"]` in **Get Suggestions List** response).

+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=

+ Response 200 (application/json)

        {
            "status": "success"
        }

+ Request Failure (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
            
+ Response 422 (application/json)

        {
            "status": "failure",
            "errors": {
                "contact_id": ["not found by id=123"]
            }
        }
        
+ Request Failure (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=

+ Response 422 (application/json)

        {
            "status": "failure",
            "errors": {
                "contact_id": ["you are not owner of contact id=123"]
            }
        }
        
+ Request Unauthorized (application/json)

+ Response 401 (application/json)

        {
            "status": "unauthorized"
        }

## Suggestions [/api/v1/suggestions]

### Get Suggestions List [GET /api/v1/suggestions]

Return first 100 contacts (not added, not ignored, not friend) in order by total score by all criteria.
        
+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
        
+ Response 200 (application/json)

        {
            "status": "success",
            "data": [
                {
                    "id": 1,
                    "first_name": null,
                    "last_name": null,
                    "display_name": "Sani El-Fishawy",
                    "zazo_mkey": "7qdanSEmctZ2jPnYA0a1",
                    "zazo_id": 1,
                    "total_score": 164,
                    "phone_numbers": ["+12345678910", "+12345678911"]
                }, {
                    "id": 2,
                    "first_name": nil,
                    "last_name": nil,
                    "display_name": "Ivan",
                    "zazo_mkey": nil,
                    "zazo_id": nil,
                    "total_score": 26,
                    "phone_numbers": ["+12345678912"]
                }
            ]
        }
        
+ Request Unauthorized (application/json)

+ Response 401 (application/json)

        {
            "status": "unauthorized"
        }    

### Recommend Contact [POST /api/v1/suggestions/recommend]

Recommend specific zazo-user (freshly invited) to others zazo-friends.

+ Parameters
    + recommendations
        + contact_mkey (string) - contact mkey to recommend
        + to_mkeys (array) - array of string of contacts (mkeys), which an another contact (**contact_mkey**) will be recommended to

+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
            
    + Body

            {
                "recommendations": {
                    "contact_mkey": "0DAQEVtmNKQiW6aoQrvo",
                    "to_mkeys": [
                        "7qdanSEmctZ2jPnYA0a1",
                        "dz4X0EvprPJO6fGysT8X"
                    ]
                }
            }

+ Response 200 (application/json)

        {
            "status": "success"
        }
        
+ Request Failure (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
            
    + Body

            {
                "recommendations": {
                    "contact_mkey": "0DAQEVtmNKQiW6aoQrvo",
                    "to_mkeys": "7qdanSEmctZ2jPnYA0a1"
                }
            }

+ Response 422 (application/json)

        {
            "status": "failure",
            "errors": {
                "raw_params": ["raw_params['to_mkeys'] must be type of Array"]
            }
        }
        
+ Request Failure (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
            
    + Body

            {
                "recommendations": {
                    "to_mkeys": [
                        "7qdanSEmctZ2jPnYA0a1",
                        "dz4X0EvprPJO6fGysT8X"
                    ]
                }
            }

+ Response 422 (application/json)

        {
            "status": "failure",
            "errors": {
                "raw_params": ["raw_params['contact_mkey'] must be type of String"]
            }
        }
        
+ Request Unauthorized (application/json)

+ Response 401 (application/json)

        {
            "status": "unauthorized"
        }

## Notifications [/api/v1/notifications]

### Get Info [GET /api/v1/notifications/{id}]

Get all information about notification by `nkey`.

+ Parameters
    + id (integer) - nkey of notification

+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": 79,
                "kind": "email",
                "state": "sent",
                "status": "added",
                "category": "fake_user_joined",
                "nkey": "d889270cec42808290ce2c9e6aed1713dd455769cfb68b7c7c80733e55a2070f",
                "contact": {
                    "id": 1149,
                    "first_name": null,
                    "last_name": null,
                    "display_name": "Ralph",
                    "zazo_mkey": null,
                    "zazo_id": null,
                    "total_score": null,
                    "vectors": [
                        {
                            "name": "mobile",
                            "value": "+12345678910",
                            "additions": {}
                        }
                    ]
                }
            }
        }

+ Request Failure (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=

+ Response 422 (application/json)

        {
            "status": "failure",
            "errors": {
                "nkey": ["nkey is incorrect"]
            }
        }
        
+ Request Unauthorized (application/json)

+ Response 401 (application/json)

        {
            "status": "unauthorized"
        }

### Add Contact [POST /api/v1/notifications/{id}/add]

Add contact of notification as friend on Zazo.

Status of contact addition (see `response["data"]["status"]` in current **Response** `200`)
may have different values: "added", "already_added", "not_added", "queued", "error".

+ Parameters
    + id (integer) - nkey of notification
    + phone_number (optional, string) - specific phone number to add contact of notification

+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=

    + Body

            {
                "phone_number": "+11234335501"
            }

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "id": "21",
                "mkey": "s0DW0LwZnY7p1x546A9n",
                "first_name": "Alan",
                "last_name": "Turing",
                "mobile_number": "+11234335501",
                "device_platform": null,
                "emails": ["admin@google.com"],
                "has_app": "false",
                "ckey": "2_21_oMGKLzfmJjFHHDbShhBg",
                "cid": "20",
                "connection_created_on": "2016-04-26T14:13:33Z",
                "connection_creator_mkey": "7qdanSEmctZ2jPnYA0a1",
                "connection_status": "established",
                "status": "added"
            }
        }

+ Request Failure (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=

+ Response 422 (application/json)

        {
            "status": "failure",
            "errors": {
                "nkey": ["nkey is incorrect"]
            }
        }
        
+ Request Unauthorized (application/json)

+ Response 401 (application/json)

        {
            "status": "unauthorized"
        }

### Ignore Contact [POST /api/v1/notifications/{id}/ignore]

Ignore contact of notification.

+ Parameters
    + id (integer) - nkey of notification

+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=

+ Response 200 (application/json)

        {
            "status": "success"
        }

+ Request Failure (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=

+ Response 422 (application/json)

        {
            "status": "failure",
            "errors": {
                "nkey": ["nkey is incorrect"]
            }
        }
        
+ Request Unauthorized (application/json)

+ Response 401 (application/json)

        {
            "status": "unauthorized"
        }

## Subscriptions [/api/v1/subscriptions]

### Get Status [GET /api/v1/subscriptions]

Get current status of subscription.

+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "status": "unsubscribed"
            }
        }

+ Request Unauthorized (application/json)

+ Response 401 (application/json)

        {
            "status": "unauthorized"
        }

### Unsubscribe [POST /api/v1/subscriptions/unsubscribe]

Unsubscribe from any future notifications (mobile and email).

+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=

+ Response 200 (application/json)

        {
            "status": "success"
        }

+ Request Unauthorized (application/json)

+ Response 401 (application/json)

        {
            "status": "unauthorized"
        }

### Subscribe [POST /api/v1/subscriptions/subscribe]

Subscribe to get friends suggestions via notifications.

+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=

+ Response 200 (application/json)

        {
            "status": "success"
        }

+ Request Unauthorized (application/json)

+ Response 401 (application/json)

        {
            "status": "unauthorized"
        }
