FORMAT: 1A
HOST: http://friendfinder.zazoapp.com/

# Zazo FriendFinder

## Authentication

The default mehtod is **HTTP Digest** with service's `username` and `password`.

The **HTTP Basic** works only for `development` environment (as in examples).

## Contacts [/api/v1/contacts]

### Add Contact List [POST]

Validate and save contact list into database.

+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
            
    + Body

            {
                "contacts": [
                    {
                        "display_name": "Sani El-Fishawy",
                        "additions": {
                            "marked_as_favorite": true
                        }
                        "vectors": [
                            {
                                "name": "mobile",
                                "value": "+16502453537",
                                "additions": {
                                    "sms_messages_sent": 15
                                }
                            }, {
                                "name": "email",
                                "value": "elfishawy.sani@gmail.com",
                                "additions": {
                                    "email_messages_sent": 23
                                }
                            }
                        ]
                    }
                ]
            }

+ Response 200 (application/json;)

        {
            "status": "success"
        }

+ Request Failure (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
            
    + Body

            {
                "contacts": [
                    {
                        "display_name": "Sani El-Fishawy",
                        "additions": {
                            "email_messages_sent": 23
                        }
                        "vectors": [
                            {
                                "name": "email",
                                "value": "asdasd@asdasd",
                                "additions": {
                                    "sms_messages_sent": 15
                                }
                            }, {
                                "name": "mobile",
                                "value": "xxxxxxxxx",
                                "additions": {
                                    "email_messages_sent": 23
                                }
                            }
                        ]
                    }
                ]
            }
            
+ Response 422 (application/json;)

        {
            "status": "failure",
            "errors": {
                "vectors": [
                    {
                        "additions": ["'sms_messages_sent' is not allowed condition for 'email' vector"],
                        "value": ["'asdasd@asdasd' has incorrect format for 'email' vector"]
                    },
                    {
                        "additions": ["'email_messages_sent' is not allowed condition for 'mobile' vector"],
                        "value": ["'xxxxxxxxx' has incorrect format for 'mobile' vector"]
                    }
                ],
                "contacts": [
                    "additions": ["'email_messages_sent' is not allowed addition"]
                ]
            }
        }
        
+ Request Unauthorized (application/json)

+ Response 401 (application/json)

        {
            "status": "unauthorized"
        }
        
## Suggestions [/api/v1/suggestions]

### Get Suggestions List [GET]

Return contacts in order by total score by all criterias.
        
+ Request Success (application/json)

    + Headers

            Authorization: Basic R0JBSGIwNDgyWXhsSjBrWXdiSVM6TzRWWENvekt1eVFOam5XUGg0MDA=
        
+ Response 200 (application/json;)

        {
            "status": "success",
            "data": [
                {
                    "first_name": null,
                    "last_name": null,
                    "display_name": "Sani El-Fishawy",
                    "zazo_mkey": "7qdanSEmctZ2jPnYA0a1",
                    "zazo_id": 1,
                    "total_score": 164
                }, {
                    "first_name": nil,
                    "last_name": nil,
                    "display_name": "Ivan",
                    "zazo_mkey": nil,
                    "zazo_id": nil,
                    "total_score": 26
                }
            ]
        }
        
+ Request Unauthorized (application/json)

+ Response 401 (application/json)

        {
            "status": "unauthorized"
        }
        