source 'https://rubygems.org'

gem 'rails'
gem 'pg'

gem 'faraday_middleware'
gem 'faraday-digestauth'

gem 'global_phone'
gem 'settingslogic'
gem 'active_model_serializers'

gem 'figaro', github: 'asux/figaro', branch: 'feature/eb-set-command'
gem 'puma'
gem 'rollbar'
gem 'newrelic_rpm'
gem 'remote_syslog_logger'
gem 'foreman'
gem 'pry-rails'

gem 'resque'
gem 'resque-web', require: 'resque_web'
gem 'whenever', require: false

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'guard'
  gem 'guard-bundler', require: false
  gem 'guard-pow', require: false
  gem 'guard-rspec', require: false
  gem 'guard-migrate'
  gem 'guard-rubocop'
  gem 'terminal-notifier-guard'
  gem 'quiet_assets'
end

group :development, :test do
  gem 'pry-rescue'
  gem 'pry-remote'
  gem 'pry-byebug', '= 1.3.3'
  gem 'rspec-rails'
end

group :test do
  gem 'database_cleaner'
  gem 'rspec-collection_matchers'
  gem 'factory_girl_rails'
  gem 'resque_spec'
  gem 'faker'
  gem 'timecop'
  gem 'webmock'
  gem 'vcr'
  gem 'shoulda-matchers', '= 2.8.0'
  gem 'simplecov', require: false
end
