source 'https://rubygems.org'

gem 'rails'
gem 'rake', '< 11'
gem 'pg'

gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'bootstrap-sass'
gem 'bootswatch-rails'
gem 'bootstrap-growl-rails'
gem 'font-awesome-rails'
gem 'simple_form'
gem 'slim-rails'
gem 'draper'
gem 'cells'
gem 'cells-slim'
gem 'kaminari'
gem 'hashie'
gem 'active_interaction', '~> 3.0'

gem 'faraday_middleware'
gem 'faraday-digestauth'

gem 'global_phone'
gem 'settingslogic'
gem 'active_model_serializers'
gem 'aasm'

gem 'zazo-tools', '~> 0.2.1',  github: 'noplanb/zazo-tools'
gem 'figaro', github: 'asux/figaro', branch: 'feature/eb-set-command'
gem 'puma'
gem 'rollbar'
gem 'newrelic_rpm'
gem 'remote_syslog_logger'
gem 'foreman'
gem 'pry-rails'

gem 'resque'
gem 'resque-web', require: 'resque_web'
gem 'whenever', require: false

group :development do
  gem 'awesome_print'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'guard'
  gem 'guard-bundler', require: false
  gem 'guard-pow', require: false
  gem 'guard-rspec', require: false
  gem 'guard-zeus'
  gem 'guard-migrate'
  gem 'guard-rubocop'
  gem 'terminal-notifier-guard'
  gem 'quiet_assets'
end

group :development, :test do
  gem 'pry-rescue'
  gem 'pry-remote'
  gem 'pry-byebug', '= 1.3.3'
  gem 'rspec-rails'
end

group :test do
  gem 'database_cleaner'
  gem 'rspec-collection_matchers'
  gem 'factory_girl_rails'
  gem 'resque_spec'
  gem 'faker'
  gem 'timecop'
  gem 'webmock', '< 2.0.0'
  gem 'vcr'
  gem 'shoulda-matchers', '= 2.8.0'
  gem 'simplecov', require: false
end
